---
- hosts: all
  become: yes
  vars:
    ruby_version: 2.4.1
    user: vagrant

  roles:
    - role: ntp
    - role: rbenv
      rbenv_user: "{{ user }}"

  tasks:
    - name: yum install Git
      yum:
        name: git
        state: latest
      notify:
      - show results

  handlers:
    - name: show results
      debug:
        var: RESULT.results
