---
- hosts: all
  become: yes

  roles:
    - role: ntp

  tasks:
    - name: yum install Git
      yum:
        name: git
        state: latest
      notify:
      - show results

  handlers:
    - name: show results
      debug:
        var: RESULT.results
